Add ipfs api client add & pin file
oursky/puttyimages-web pull request #25
Opened 2018-06-08 10:31 UTC by inDream

Connects likecoin/puttyimages-web#1

2018-06-11 04:10 UTC, rickmak requested changes
Comment message should be in this format: https://gitmoji.carloscuesta.me/

2018-06-11 04:10 UTC, rickmak commented on server/ipfs.js
> +  clients.push({ api, host });
Please use return instead of modifying the global.

2018-06-11 04:10 UTC, rickmak commented on server/ipfs.js
> +    cat: (path) => Promise.race(clients.map(({ api }) => api.files.cat(path))),
Since we only want to cat one file, using `race` here will yield to unnecessary IO with the IPFS.

Here we should just pick one node and cat.

2018-06-11 04:10 UTC, rickmak commented on server/ipfs.js
> +      const masterNodes = clients.filter(({ host }) => master.indexOf(host) > -1);
`clients` and `masterNodes` should be same level variable, they are same level concept.

In addition, in our offline discussion, `masterNodes` should be identical to client if the setting is missing. Currently this logic is missing.

2018-06-11 04:10 UTC, rickmak commented on server/ipfs.js
> +    port: process.env.IPFS_PORT || '5001',
We need to change the way that PORT config too. I don't think assuming same IPFS_PORT across all node makes much sense.

2018-06-11 04:10 UTC, rickmak commented
We need a basic test case too.

2018-06-12 04:21 UTC, rickmak requested changes
Not mergable on using global state in class.

2018-06-12 04:21 UTC, rickmak commented on server/ipfs.js
> +      const masterNodes = this.clients.filter(({ host }) => master.indexOf(host) > -1);
class should not access outside variable if possible.

2018-06-12 04:21 UTC, rickmak commented on server/ipfs.js
> +  const [, protocol, host, port] = config.match(/(\w+):\/\/(\w+):(\w+)/);
Let use node url module instead of custom regex.

2018-06-12 04:21 UTC, rickmak commented on server/ipfs.js
> +  }
I am not a fan on lazy init. Prefer to make instance ready at server boot time is better.

2018-06-12 04:44 UTC, inDream commented
@rickmak formatted code

2018-06-12 05:03 UTC, rickmak commented
Merge via 7a8190f

2018-06-12 05:03 UTC, closed without merging

2018-06-12 05:03 UTC, rickmak commented
Logic is more blocking then format.